import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TwSizeIndicator from '@/app/_components/TwSizeIndicator'
import { ToastProvider } from '@/app/_providers/toast-provider'
import { ThemeProvider } from '@/app/_providers/theme-provider'
import { ModalProvider } from '@/app/_providers/modal-provider'
import { DialogProvider } from '@/app/_providers/dialog-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <TwSizeIndicator />
          <ToastProvider />
          <ModalProvider />
          {/* <DialogProvider /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
